name: light_logger
description: A easy and light logger for Dart & Flutter
version: 0.0.1
homepage: https://teta.so
repository: https://github.com/teta-so/dart_logger

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:

dev_dependencies:
  flutter_lints: ^2.0.1

